aonez/Keka

Context-Menu/简体中文/HOWTO.txt

Update HOWTO.txt to Simplified Chinese

---

Context-Menu/polish/Compress with Keka.workflow/Contents/Info.plist
Context-Menu/polish/ZROB-TO-SAM.txt
Translations/Current Translations/pl.lproj/Credits.html
Translations/Current Translations/pl.lproj/Localizable.strings
Translations/Current Translations/pl.lproj/advanced.xib
Translations/Current Translations/pl.lproj/extraction.xib
Translations/Current Translations/pl.lproj/main.xib
Translations/Current Translations/pl.lproj/preferences.xib

Translated all strings to Polish, then tested in Xcode. Anyway, still
might contain some typos to be corrected…

Keka - complete Polish translation

---

Translations/Current Translations/pl.lproj/Localizable.strings

Translated all strings to Polish, tested in Xcode, pushed wrong files, then corrected some strings. Anyway, correct still might contain some typos to be corrected…

Update for Polish translation

---

Services/Keka Automatic.workflow/Contents/Resources/zh-Hant.lproj/ServicesMenu.strings
Services/Keka Compression.workflow/Contents/Resources/zh-Hant.lproj/ServicesMenu.strings
Services/Keka Extraction.workflow/Contents/Resources/zh-Hant.lproj/ServicesMenu.strings
Translations/Common/Translators.html

Adding rest of the things in
First pull: [https://github.com/aonez/Keka/pull/71](https://github.com/aonez/Keka/pull/71)

zh-Hant translation #2

---

Translations/pl.lproj/InfoPlist.strings
Translations/pl.lproj/preferences.strings

Release Candidate Update 2

---

Translations/Web/lang_pt.php

Keka's website pt-BR translation.

Site translation (pt)

---

Translations/Web/lang_pt.php

Minor layout corrections and copyright text adjustment.
Signed-off-by: Victor <contact@brlingo.com>

Minor corrections for BR

---

Translations/Common/Translators.html

- Fixed indent
- Added Turkish translator
- Added language info as a comment before each translators
- Translator list is sorted alphabetically. (in English)

Added Turkish translator

---

Translations/Web/lang_tr.php

Turkish web translation by @bariskayadelen

---

Translations/Web/lang_ru.php

I thought it's weird that the app is translated while the website isn't

Russian website translation

---

Translations/ru.lproj/preferences.strings

Fix typo in russian localization

---

Translations/it.lproj/advanced.strings

Change string: "Archive as single files" -> "Archive items separately"

(Italian) Update advanced.strings

---

Translations/it.lproj/InfoPlist.strings
Translations/it.lproj/preferences.strings

(Italian) Update localization

---

Translations/Common/Translators.html
Translations/Web/lang_ja.php
Translations/ja.lproj/Credits.html
Translations/ja.lproj/InternetAccessPolicy.strings
Translations/ja.lproj/advanced.strings
Translations/ja.lproj/preferences.strings

Hi @aonez.
I add Japanese web translation and update some Japanese Keka translation.
Could you please review my PR?

Add Japanese web translation and update some Japanese Keka translation.

---

Translations/cs.lproj/Localizable.strings
Translations/cs.lproj/advanced.strings
Translations/cs.lproj/preferences.strings

Fixed a few grammatical and stylistic problems

Small adjustments to the Czech translation

---

Translations/it.lproj/main.strings

Update main.strings (Italian)

---

Translations/it.lproj/Localizable.strings

Update Localizable.strings (IT)

---

Translations/Common/Translators.html
Translations/de.lproj/InternetAccessPolicy.strings
Translations/de.lproj/Localizable.strings

This pull requests adds German translations for the password match warning. Additionally it localizes the IAP for Little Snitch to German.

Adds missing German translations

---

README.md

The link for the "one of the reasons" is broken so I added the link through web.archive

Update README to change "one of the reasons" url

---

Translations/it.lproj/FinderExtensionLocalizable.strings

Update FinderExtensionLocalizable.strings (It)

Update FinderExtensionLocalizable.strings (It)

---

Translations/it.lproj/advancedWindowPopover.strings

Fixed literal
"Remove this window" -> "Remove this configuration"

Update advancedWindowPopover.strings (IT)

---

Translations/it.lproj/InfoPlist.strings
Translations/it.lproj/Localizable.strings
Translations/it.lproj/logPopoverView.strings
Translations/it.lproj/main.strings

Update Italian localization

---

Translations/ru.lproj/InfoPlist.strings
Translations/ru.lproj/Localizable.strings
Translations/ru.lproj/logPopoverView.strings

Russian translation updated

---

Translations/Web/lang_ko.php

- Modified after feedback received.
- Translated Korean and translated the existing translation more naturally.

Translate Korean.

---

Translations/bg.lproj/Localizable.strings
Translations/ca.lproj/Localizable.strings
Translations/cs.lproj/Localizable.strings
Translations/de.lproj/Localizable.strings
Translations/el.lproj/Localizable.strings
Translations/en-GB.lproj/Localizable.strings
Translations/en.lproj/Localizable.strings
Translations/es.lproj/Localizable.strings
Translations/fr.lproj/Localizable.strings
Translations/hu.lproj/Localizable.strings
Translations/it.lproj/Localizable.strings
Translations/ja.lproj/Localizable.strings
Translations/ko.lproj/Localizable.strings
Translations/nb.lproj/Localizable.strings
Translations/nl.lproj/Localizable.strings
Translations/pl.lproj/Localizable.strings
Translations/pt-BR.lproj/Localizable.strings
Translations/pt-PT.lproj/Localizable.strings
Translations/ru.lproj/Localizable.strings
Translations/sv.lproj/Localizable.strings
Translations/tr.lproj/Localizable.strings
Translations/uk.lproj/Localizable.strings
Translations/vi.lproj/Localizable.strings
Translations/zh-Hans.lproj/Localizable.strings
Translations/zh-Hant.lproj/Localizable.strings

Fixes strings Prepearing-> Preparing

Prepearing-> Preparing

---

README.md

Fixed Wiki - README.md cannal -> channel

cannal -> channel

---

Translations/README.md

Fixed Translation - README.md prefered -> preferred

prefered -> preferred

---

Translations/Common/Translators.html

Fixed Translators.html български -> Български

български -> Български

---

Translations/Web/lang_bg.php
Translations/Web/lang_en.php
Translations/Web/lang_es.php
Translations/Web/lang_it.php
Translations/Web/lang_ja.php
Translations/Web/lang_ko.php
Translations/Web/lang_nb.php
Translations/Web/lang_pl.php
Translations/Web/lang_pt-br.php
Translations/Web/lang_pt-pt.php
Translations/Web/lang_ru.php
Translations/Web/lang_tr.php
Translations/Web/lang_uk.php
Translations/Web/lang_vi.php
Translations/Web/lang_zh-cn.php
Translations/Web/lang_zh-tw.php

Fixes lang_*.php plataform -> platform

plataform -> platform

---

.github/labeler.yml

Fixed labeler.yml - Quotation marks

Fixed labeler.yml - Quotation marks

---

Translations/README.md

Fixed missing points in README.md

Fixed missing points in README.md

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Your "README.md" is taken as a basis. So that everything is in the same style.
**Before "bug_report.md"**
**After "bug_report.md"**
**Before "feature_request.md"**
**After "feature_request.md"**
**Your "README.md" is taken as a basis. So that everything is in the same style.**
P.S.: I know that these changes do not affect the speed and quality of the program. I did it so that there was a uniform style and pleasant to the eyes.

Improvements to "bug_report.md" and "feature_request.md"

---

Translations/it.lproj/Localizable.strings
Translations/it.lproj/preferences.strings

for "Adding tips in MAS version of Keka"

Update of the Italian localization

---

Translations/Web/lang_zh-cn.php
Translations/Web/lang_zh-tw.php

Could you also add this pull request with tag `hacktoberfest-accepted`? I want to participate in[ Hacktoberfest](https://hacktoberfest.digitalocean.com/). Thank you!

update Chinese translations

---

Translations/it.lproj/InfoPlist.strings

Access request description strings (Italian)

---

Translations/it.lproj/FinderExtensionLocalizable.strings

Update FinderExtensionLocalizable.strings

Added missing context menu item string (Italian)

---

Translations/it.lproj/preferences.strings

Option to track external volumes with Finder appx (Italian)

---

Translations/fr.lproj/FinderExtensionLocalizable.strings

Update FinderExtensionLocalizable.strings in French

Update french translations

---

Translations/it.lproj/preferences.strings

Update preferences.strings (Italian)

Added option for disabling always using tarball (Italian)

---

Translations/it.lproj/FinderExtensionLocalizable.strings
Translations/it.lproj/InfoPlist.strings
Translations/it.lproj/Localizable.strings

Update InfoPlist.strings, FinderExtensionLocalizable.strings and Localizable.strings

Italian localization update

---

Translations/it.lproj/Localizable.strings

Update Localizable.strings (Italian)

Italian MAS tips translations

---

Translations/it.lproj/Localizable.strings

Update Localizable.strings (Italian)

Fixed Italian MAS tip strings character limit

---

Translations/cs.lproj/FinderExtensionLocalizable.strings
Translations/cs.lproj/InfoPlist.strings
Translations/cs.lproj/Localizable.strings
Translations/cs.lproj/loveView.strings
Translations/cs.lproj/preferences.strings

Translated MAS strings & access requests to Czech, fixed a slight typo.
Great job on developing Keka so quickly! 😊

Translated MAS strings & access requests

---

Translations/it.lproj/Localizable.strings
Translations/it.lproj/preferences.strings

Update Localizable.strings and preferences.strings (Italian)

Strings for Finder Extension customization list (Italian)

---

Translations/it.lproj/Localizable.strings
Translations/it.lproj/preferences.strings

For UNRAR 6.00 - Update Localizable.strings (Italian)
Also includes "**Finder Extension status strings (Italian)**"
Update Localizable.strings and preferences.strings (Italian)

New UNRAR error 12 definition (Italian)

---

Translations/it.lproj/Localizable.strings

Update Localizable.strings (Italian)

String no file access to the SOURCE -> DESTINATION (Italian)

---

Translations/it.lproj/Localizable.strings

Update Localizable.strings (Italian)

Update helper string (Italian)

---

Translations/Web/lang_vi.php

Update Vietnamese translation

---

Translations/zh-Hant.lproj/InfoPlist.strings
Translations/zh-Hant.lproj/Localizable.strings
Translations/zh-Hant.lproj/advanced.strings
Translations/zh-Hant.lproj/advancedWindowPopover.strings
Translations/zh-Hant.lproj/preferences.strings

Hi,
I made some tweaks to make translation more fluently.
Could you take a look with this? Thanks!
Best regards,
Yi-Jyun Pan.

l10n(zh_TW): tweak translation

---

Translations/zh-Hant.lproj/Localizable.strings

update zh_TW translations to ac91f49

---

Translations/zh-Hant.lproj/preferences.strings

l10n(zh_TW): update translation to dd4b5eb7cf

---

Translations/it.lproj/preferences.strings

Update preferences.strings (Italian)

Use short tarball extensions option in Preferences (Italian)

---

Translations/pt-BR.lproj/Localizable.strings
Translations/pt-BR.lproj/preferences.strings

My apologies for the hiatus… Cheers!

New BR translations.

---

Translations/Web/lang_zh-tw.php

thanks 😆❤️😊
note: `ready-for-merging`

l10n(web/zh-tw): update and review localization

---

Translations/en-GB.lproj/InfoPlist.strings
Translations/en-GB.lproj/preferences.strings

Please let me know if I missed anything.

Updated British English Localisation

---

Translations/it.lproj/Localizable.strings
Translations/it.lproj/loveView.strings

Update Localizable.strings and loveView.strings

Rate & Review options (MAS) - Italian

---

Translations/Common/Translators.html
Translations/ko.lproj/Localizable.strings
Translations/ko.lproj/loveView.strings
Translations/ko.lproj/preferences.strings

Update Korean Translation

---

Translations/it.lproj/preferences.strings

Update preferences.strings (IT)

Option to rename extension from intermediate folder (IT)

---

Translations/it.lproj/loveView.strings

Restore purchases button (for monthly tips) - Italian

---

Translations/zh-Hant.lproj/loveView.strings
Translations/zh-Hant.lproj/preferences.strings

l10n(zh_TW): completed all translation (~b5318b8)

---

Translations/Common/Translators.html
Translations/Web/lang_ru.php
Translations/ru.lproj/InfoPlist.strings
Translations/ru.lproj/Localizable.strings
Translations/ru.lproj/loveView.strings
Translations/ru.lproj/preferences.strings

Following https://github.com/aonez/Keka/commit/b3a2a5e6fdf29bc3995fadcd1aa76aa514a661a8, I have localized new strings in Russian.
Additionally, I have updated my email and website addresses.

Update Russian locale

---

Translations/it.lproj/preferences.strings

Update preferences.strings (IT)

New options to customize Dock icon (IT)

---

Translations/Web/lang_vi.php
Translations/vi.lproj/loveView.strings
Translations/vi.lproj/preferences.strings

+ Update Vietnamese translation.

New options to customize Dock icon (VI)

---

Translations/pt-BR.lproj/InfoPlist.strings
Translations/pt-BR.lproj/loveView.strings
Translations/pt-BR.lproj/preferences.strings

Here are the new strings! Cheers!

New translations for BR.

---

Translations/ru.lproj/Localizable.strings

That was hard considering how long some Russian words are :sweat_smile:

Fix Russian strings

---

Translations/zh-Hant.lproj/preferences.strings

* commit b3a2a5e6fdf29bc3995fadcd1aa76aa514a661a8
* commit 0572ca3661d7c4f75385e541a5969caa1ffa0c8a
Thanks!

l10n(zh_TW): update translation

---

Translations/ru.lproj/Localizable.strings
Translations/uk.lproj/Localizable.strings

**Ukrainian:** 
- Edited translations in MAS tips due https://github.com/aonez/Keka/pull/726#discussion_r750536415
- Reworked illogical or difficult-to-understand translations
**Russian:**
- Reworked illogical or difficult-to-understand translations

Updated Ukrainian and Russian localizations

---

Translations/pl.lproj/preferences.strings

Now I know what 'squish' means! :+1:

Squish update

---

Translations/ru.lproj/InfoPlist.strings

"Electronic Book" = "Электронная книга"
"Apple Archive" = "Архив Apple"

Update InfoPlist.strings (RU)

---

Translations/Web/lang_it.php
Translations/it.lproj/InfoPlist.strings

Update InfoPlist.strings (IT) and lang_it.php

Electronic Book support + Added web download & maintenance strings (IT)

---

Translations/de.lproj/InfoPlist.strings

See https://github.com/aonez/Keka/commit/9060b6e6a707d8097e34a6fcc7099fbb45ae03d2

Translate NSDownloadsFolderUsageDescription for German

---

Translations/it.lproj/FinderExtensionLocalizable.strings
Translations/it.lproj/InfoPlist.strings
Translations/it.lproj/Localizable.strings
Translations/it.lproj/preferences.strings

New strings from 1.2.53-beta.1 (Italian)

New strings from 1.2.53-beta.1 (IT)

---

Translations/tr.lproj/FinderExtensionLocalizable.strings
Translations/tr.lproj/InfoPlist.strings
Translations/tr.lproj/Localizable.strings
Translations/tr.lproj/advanced.strings
Translations/tr.lproj/preferences.strings

Update Turkish translation

---

Translations/tr.lproj/Localizable.strings

Line 12 translated. 
"Passwords" = "Parolalar";

Update Turkish translation in Localizable.strings

---

Translations/hu.lproj/FinderExtensionLocalizable.strings
Translations/hu.lproj/InfoPlist.strings
Translations/hu.lproj/Localizable.strings
Translations/hu.lproj/preferences.strings

Hi,
Here are the updated strings.
+1: I couldn't find "Passwords".

updated hungarian translations

---

Translations/it.lproj/Localizable.strings

Some strings translated

---

Translations/sv.lproj/FinderExtensionLocalizable.strings
Translations/sv.lproj/InfoPlist.strings
Translations/sv.lproj/Localizable.strings
Translations/sv.lproj/preferences.strings

Swedish update

---

Translations/de.lproj/Localizable.strings
Translations/de.lproj/preferences.strings

#1080 Update German translation for password handling.

---

Translations/it.lproj/preferences.strings

Update preferences.strings (IT)

Update preferences.strings (IT)

---

Translations/zh-Hant.lproj/preferences.strings

commit bede2917e17187dd4c0cdaf9a3319fbd04194d36
Thanks! ❤️

l10n: zh_TW: update translation to latest

---

Translations/de.lproj/InfoPlist.strings

Update German translation

---

Translations/it.lproj/main.strings

"Settings" instead of "Preferences" in macOS 13 (IT)

---

Translations/zh-Hant.lproj/preferences.strings

commit d951e060c3bc69ea5b3d3b6d84e92f5720c33359

l10n: zh_TW: “Show the password”

---

Translations/Web/lang_bg.php
Translations/bg.lproj/Credits.strings
Translations/bg.lproj/advanced.strings

Changed due to untranslated strings

Little changes

---

Translations/sv.lproj/preferences.strings

I found two spelling errors in the english source. 
Jyq-vC-L5r.title 
equiped should be equipped 
Eficiency should be Efficiency

Added new features, also found two issues in the original text labels

---

Translations/pt-BR.lproj/main.strings
Translations/pt-BR.lproj/preferences.strings

Hi aOne!
Apologies for the hiatus, but here are what I believe to be the pending strings. Let me know if I miss anything, ok?
Salud!

Translated missing strings

---

.github/ISSUE_TEMPLATE/bug_report.md

Just a small edit of bug report issue template. :)

Deleted extra character from ellipsis in ISSUE_TEMPLATE

---

Translations/it.lproj/Localizable.strings

Enable external volumes access extra info for MAS (IT)

---

Translations-iOS/README.md

Fixed typo in Translations-iOS/README.md

Fixed typo in Translations-iOS/README.md

---

Translations/it.lproj/Localizable.strings
Translations/it.lproj/advanced.strings
Translations/it.lproj/preferences.strings

Strings for verify option and AAR encryption (IT)

Strings for verify option and AAR encryption (IT)

---

Translations/zh-Hant.lproj/Localizable.strings
Translations/zh-Hant.lproj/advanced.strings
Translations/zh-Hant.lproj/preferences.strings

- Strings for verify option and AAR encryption

l10n: zh_TW: update to d14c31d

---

Translations/it.lproj/preferences.strings

Update preferences.strings (IT)

Automatically install new updates check in Prefs. (IT)

---

Translations/it.lproj/Localizable.strings
Translations/it.lproj/advanced.strings

Added DMG format selection (IT)

Added DMG format selection (IT)

---

Translations-iOS/Alternative-Strings-Files/zh-Hans.lproj/InfoPlist.strings
Translations-iOS/Alternative-Strings-Files/zh-Hans.lproj/Localizable.strings
Translations-iOS/zh-Hans.xcloc/Localized Contents/zh-Hans.xliff
Translations/Web/lang_zh-cn.php

check CHS translation

---

Translations/Web/lang_it.php

Updated web with iOS strings (IT)

---

Translations-iOS/Alternative-Strings-Files/it.lproj/InfoPlist.strings
Translations-iOS/Alternative-Strings-Files/it.lproj/Localizable.strings

Added Volume strings to iOS translation (IT)

Added Volume strings to iOS translation (IT)

---

Translations/zh-Hans.lproj/preferences.strings

- Verify compression integrity -> 检查压缩完整性
- Automatically install new updates -> 自动安装更新

Update Simplified Chinese localization

---

Translations/cs.lproj/Localizable.strings
Translations/cs.lproj/advanced.strings
Translations/cs.lproj/preferences.strings

Hello,
I prepare some fixes/typos and unify some strings.

Czech localization fixies

---

Translations/Common/Translators.html
Translations/it.lproj/InfoPlist.strings

Squashfs Filesystem Archive document type string (IT)

Squashfs Filesystem Archive document type string (IT)

---

Translations/cs.lproj/preferences.strings

Czech tiny fixies

---

Translations/Common/Translators.html
Translations/de.lproj/preferences.strings

Added some German translations that were still missing.

add missing German translations

---

Translations/it.lproj/Localizable.strings

LRZIP + Password limit string (IT)

---

Translations/cs.lproj/Localizable.strings

LRZIP + Password limit string (cs)

---

Translations/tr.lproj/InfoPlist.strings
Translations/tr.lproj/Localizable.strings
Translations/tr.lproj/advanced.strings
Translations/tr.lproj/preferences.strings

Turkish Translation updated.

---

Translations/zh-Hans.lproj/Localizable.strings

- Add translation for LRZIP + Password limit string

LRZIP + Password limit string (SC)

---

Translations-iOS/Alternative-Strings-Files/zh-Hans.lproj/InfoPlist.strings
Translations/Web/lang_zh-cn.php

Update CHS translation

---

Translations-macOS/de.lproj/Localizable.strings
Translations-macOS/de.lproj/advanced.strings

Update of missing strings

---

Translations-Web/lang_cs.php

Only minor/cosmetic fixies.
Added Translator errata 👍

First fix czech web localisation

---

Translations-Web/lang_sv.php
Translations-iOS/Alternative-Strings-Files/sv.lproj/Localizable.strings
Translations-macOS/Common/Translators.html

Updated link and future strings

X > Threads

---

.github/workflows/upstreamSync.yml

Action template for contributors.
Action which sync contributor's own fork with upstream repo every afternoon.

Add upstreamSync action

---

Translations-Web/lang_zh-tw.php
Translations-iOS/zh-Hant.xcloc/Localized Contents/zh-Hant.xliff
Translations-macOS/zh-Hant.lproj/Credits.strings
Translations-macOS/zh-Hant.lproj/Localizable.strings
Translations-macOS/zh-Hant.lproj/advanced.strings

Update (and review) the website, macOS, iOS translation.
I removed the space between Chinese and English characters in iOS translation, since iOS and macOS now add 1/4 spacing between these characters now.

Keka translation (zh-TW, 2024-01-21)

---

Translations-iOS/Alternative-Strings-Files/it.lproj/InfoPlist.strings
Translations-iOS/Alternative-Strings-Files/it.lproj/Localizable.strings

[iOS] Added new strings (IT)

---

Translations-macOS/it.lproj/InfoPlist.strings

Added MDZ (Commodore Amiga MOD Archive) - (IT)

Added MDZ (Commodore Amiga MOD Archive) - (IT)

---

Translations-macOS/it.lproj/Localizable.strings
Translations-macOS/it.lproj/advanced.strings
Translations-macOS/it.lproj/preferences.strings

Strings for new features (IT)

---

Translations-Web/lang_vi.php
Translations-macOS/vi.lproj/Localizable.strings
Translations-macOS/vi.lproj/advanced.strings
Translations-macOS/vi.lproj/preferences.strings

Hi I had check it out and found out some translate are confused to user and some string is not translated.

Update Vietnamese translation for Keka

---

Translations-iOS/zh-Hant.xcloc/Localized Contents/zh-Hant.xliff
Translations-macOS/zh-Hant.lproj/InfoPlist.strings
Translations-macOS/zh-Hant.lproj/Localizable.strings
Translations-macOS/zh-Hant.lproj/advanced.strings
Translations-macOS/zh-Hant.lproj/main.strings
Translations-macOS/zh-Hant.lproj/preferences.strings

- **l10n(iOS/zh-TW): Update to 51b3800276**
- **l10n(macOS/zh-TW): Update to fa6007027a**

l10n: zh-TW: Update Keka translation

---

Translations-iOS/Alternative-Strings-Files/cs.lproj/AppShortcuts.strings
Translations-iOS/Alternative-Strings-Files/cs.lproj/Localizable.strings

Upodate Czech resources

---

Translations-iOS/Alternative-Strings-Files/it.lproj/AppShortcuts.strings
Translations-iOS/Alternative-Strings-Files/it.lproj/Localizable.strings

[iOS] Shortcuts and last versions strings (IT)

[iOS] Shortcuts and last versions strings (IT)

---

Translations-Web/lang_ru.php
Translations-macOS/ru.lproj/preferences.strings

- corrections to current version
- new translation to the upcoming 1.4.0

RU-translation updates

---

Translations-macOS/it.lproj/InfoPlist.strings

[macOS] New format strings (v1.4.0) - IT

[macOS] New format strings (v1.4.0) - IT

---

Translations-Web/lang_ko.php
Translations-iOS/ko.xcloc/Localized Contents/ko.xliff
Translations-iOS/ko.xcloc/contents.json
Translations-macOS/Common/Translators.html
Translations-macOS/ko.lproj/InfoPlist.strings
Translations-macOS/ko.lproj/Localizable.strings
Translations-macOS/ko.lproj/advanced.strings
Translations-macOS/ko.lproj/preferences.strings

- Updated translations for macOS & Web.
- Added 'ko.xcloc' file for iOS.

Update KO translation

---

Translations-iOS/zh-Hant.xcloc/Localized Contents/zh-Hant.xliff
Translations-macOS/zh-Hant.lproj/InfoPlist.strings
Translations-macOS/zh-Hant.lproj/Localizable.strings

- **l10n(macOS/zh-TW): Update translation**
- **l10n(iOS/zh-TW): Update translation**

l10n: zh-TW: Keka translation (2024-05-23)

---

Translations-macOS/it.lproj/FinderExtensionLocalizable.strings
Translations-macOS/it.lproj/Localizable.strings
Translations-macOS/it.lproj/preferences.strings

[macOS] New encryption options (IT)

[macOS] New encryption options (IT)

---

Translations-macOS/it.lproj/Localizable.strings
Translations-macOS/it.lproj/preferences.strings

[macOS] Preferences new default action (IT)

[macOS] Preferences new default action (IT)

---

Translations-macOS/en.lproj/InternetAccessPolicy.strings
Translations-macOS/ja.lproj/Localizable.strings
Translations-macOS/ja.lproj/preferences.strings

translations of newly added strings for 1.4.3 (5464)
and no localisable strings found below...(in preferences.strings)
> Keka will decide whether to compress or uncompress based on the file extension and format for unrecognized files. This is the recommended option.

ja translate update

---

Translations-macOS/pt-BR.lproj/InfoPlist.strings
Translations-macOS/pt-BR.lproj/Localizable.strings
Translations-macOS/pt-BR.lproj/advanced.strings
Translations-macOS/pt-BR.lproj/preferences.strings

Pending BR translations for 1.4.3

---

Translations-macOS/zh-Hans.lproj/Localizable.strings
Translations-macOS/zh-Hans.lproj/loveView.strings

I updated these localizable files because some of them were inaccurate, and others contained Chinese dialects that are not widely understood across the different Chinese-speaking countries.

Localization Optimization of Chinese Simplified

---

Translations-macOS/it.lproj/preferences.strings

[macOS] Activate Keka when starting new operation (IT)

[macOS] Activate Keka when starting new operation (IT)

---

Translations-macOS/ja.lproj/Localizable.strings
Translations-macOS/ja.lproj/preferences.strings

Japanese translation update

---

Translations-macOS/zh-Hant.lproj/InfoPlist.strings
Translations-macOS/zh-Hant.lproj/preferences.strings

Reference: 98c0114e86bd6ff75a539ab04b5d1ccdfcd7679b

l10n(macOS/zh-Hant): Update translation

---

Translations-macOS/it.lproj/preferences.strings

Resizable window + ignore trailing data options (IT)

Resizable window + ignore trailing data options (IT)

---

Translations-iOS/Alternative-Strings-Files/it.lproj/Localizable.strings

[iOS] Translations updated (IT)

---

Translations-macOS/pl.lproj/InfoPlist.strings

Updated missing translations with proper Polish texts

Update InfoPlist.strings with missing translations

---

Translations-macOS/it.lproj/InternetAccessPolicy.strings

Update InternetAccessPolicy.strings (IT)

Added Github to IAP file (IT)

---

Translations-macOS/it.lproj/Localizable.strings

VoiceOver strigs for show/hide password button (IT)

---

Translations-iOS/zh-Hant.xcloc/Localized Contents/zh-Hant.xliff

Just a minor issue of the Traditional Chinese translation.

Fix a small translation issue for zh-Hant

---

Translations-iOS/Alternative-Strings-Files/ja.lproj/Localizable.strings
Translations-iOS/ja.xcloc/Localized Contents/ja.xliff
Translations-macOS/ja.lproj/InfoPlist.strings
Translations-macOS/ja.lproj/Localizable.strings
Translations-macOS/ja.lproj/preferences.strings

Japanese Localize Update (macOS/iOS)

---

Translations-macOS/pt-BR.lproj/InfoPlist.strings
Translations-macOS/pt-BR.lproj/Localizable.strings

Second try

---

Translations-macOS/it.lproj/InfoPlist.strings

Added XAR Archive (IT)
